import {
  Images1,
  Images2,
  Images3,
  Images4,
  Images5,
  Images6,
  Images7,
  Images8,
} from './assest.js';
     const CardsData = [
    {
        img: Images1,
        img1: Images1,
        img2: Images1,
        img3: Images1,
        img4: Images1,
        discount: "-30%",
        newItem: "",
        productName: "Syltherine",
        shortDescription: "Stylish cafe chair",
        price: "Rp 2.500.000",
        fixPrice: "Rp 3.500.000",
        review: "4.7",
        amounthReview: "200",
        customerReview: "4",
        sku: "SS001",
        category: "Sofas",
        tags: "Sofa, Chair, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images2,
        img1: Images2,
        img2: Images2,
        img3: Images2,
        img4: Images2,
        discount: "-30%",
        newItem: "",
        productName: "Leviosa",
        shortDescription: "Stylish cafe chair",
        price: "Rp 2.500.000",
        fixPrice: "Rp 3.500.000",
        review: "4.6",
        amounthReview: "205",
        customerReview: "3",
        sku: "SS002",
        category: "Chair",
        tags: "Sofa, Chair, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images3,
        img1: Images3,
        img2: Images3,
        img3: Images3,
        img4: Images3,
        discount: "-50%",
        newItem: "",
        productName: "Lolito",
        shortDescription: "Luxury big sofa",
        price: "Rp 7.000.000",
        fixPrice: "Rp 14.000.000",
        review: "4.8",
        amounthReview: "405",
        customerReview: "8",
        sku: "SS003",
        category: "Sofa",
        tags: "Sofa, Chair, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images4,
        img1: Images4,
        img2: Images4,
        img3: Images4,
        img4: Images4,
        discount:  "",
        newItem: "New",
        productName: "Respira",
        shortDescription: "Outdoor bar table and stool",
        price: "Rp 500.000",
        fixPrice: "",
        review: "4",
        amounthReview: "105",
        customerReview: "2",
        sku: "SS004",
        category: "Table",
        tags: "Table, Chair, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images5,
        img1: Images5,
        img2: Images5,
        img3: Images5,
        img4: Images5,
        discount:  "",
        newItem: "",
        productName: "Grifo",
        shortDescription: "Night lamp",
        price: "Rp 1.500.000",
        fixPrice: "",
        review: "4.3",
        amounthReview: "156",
        customerReview: "3",
        sku: "SS005",
        category: "Lamp",
        tags: "Lamp, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images6,
        img1: Images6,
        img2: Images6,
        img3: Images6,
        img4: Images6,
        discount:  "",
        newItem: "New",
        productName: "Muggo",
        shortDescription: "Small mug",
        price: "Rp 1.500.000",
        fixPrice: "",
        review: "5",
        amounthReview: "456",
        customerReview: "5",
        sku: "SS006",
        category: "Mug",
        tags: "Mug, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images7,
        img1: Images7,
        img2: Images7,
        img3: Images7,
        img4: Images7,
        discount:  "-50%",
        newItem: "",
        productName: "Pingky",
        shortDescription: "Cute bed set",
        price: "Rp 7.000.000",
        fixPrice: "Rp 14.000.000",
        review: "4.4",
        amounthReview: "456",
        customerReview: "6",
        sku: "SS007",
        category: "Bed",
        tags: "Bed, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images8,
        img1: Images8,
        img2: Images8,
        img3: Images8,
        img4: Images8,
        discount:  "",
        newItem: "New",
        productName: "Potty",
        shortDescription: "Minimalist flower pot",
        price: "Rp 500.000",
        fixPrice: "",
        review: "4.4",
        amounthReview: "156",
        customerReview: "2",
        sku: "SS008",
        category: "Flower",
        tags: "Flower, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images1,
        img1: Images1,
        img2: Images1,
        img3: Images1,
        img4: Images1,
        discount: "-30%",
        newItem: "",
        productName: "Syltherine",
        shortDescription: "Stylish cafe chair",
        price: "Rp 2.500.000",
        fixPrice: "Rp 3.500.000",
        review: "4.7",
        amounthReview: "200",
        customerReview: "4",
        sku: "SS001",
        category: "Sofas",
        tags: "Sofa, Chair, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images2,
        img1: Images2,
        img2: Images2,
        img3: Images2,
        img4: Images2,
        discount: "-30%",
        newItem: "",
        productName: "Leviosa",
        shortDescription: "Stylish cafe chair",
        price: "Rp 2.500.000",
        fixPrice: "Rp 3.500.000",
        review: "4.6",
        amounthReview: "205",
        customerReview: "3",
        sku: "SS002",
        category: "Chair",
        tags: "Sofa, Chair, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images3,
        img1: Images3,
        img2: Images3,
        img3: Images3,
        img4: Images3,
        discount: "-50%",
        newItem: "",
        productName: "Lolito",
        shortDescription: "Luxury big sofa",
        price: "Rp 7.000.000",
        fixPrice: "Rp 14.000.000",
        review: "4.8",
        amounthReview: "405",
        customerReview: "8",
        sku: "SS003",
        category: "Sofa",
        tags: "Sofa, Chair, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images4,
        img1: Images4,
        img2: Images4,
        img3: Images4,
        img4: Images4,
        discount:  "",
        newItem: "New",
        productName: "Respira",
        shortDescription: "Outdoor bar table and stool",
        price: "Rp 500.000",
        fixPrice: "",
        review: "4",
        amounthReview: "105",
        customerReview: "2",
        sku: "SS004",
        category: "Table",
        tags: "Table, Chair, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images5,
        img1: Images5,
        img2: Images5,
        img3: Images5,
        img4: Images5,
        discount:  "",
        newItem: "",
        productName: "Grifo",
        shortDescription: "Night lamp",
        price: "Rp 1.500.000",
        fixPrice: "",
        review: "4.3",
        amounthReview: "156",
        customerReview: "3",
        sku: "SS005",
        category: "Lamp",
        tags: "Lamp, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images6,
        img1: Images6,
        img2: Images6,
        img3: Images6,
        img4: Images6,
        discount:  "",
        newItem: "New",
        productName: "Muggo",
        shortDescription: "Small mug",
        price: "Rp 1.500.000",
        fixPrice: "",
        review: "5",
        amounthReview: "456",
        customerReview: "5",
        sku: "SS006",
        category: "Mug",
        tags: "Mug, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images7,
        img1: Images7,
        img2: Images7,
        img3: Images7,
        img4: Images7,
        discount:  "-50%",
        newItem: "",
        productName: "Pingky",
        shortDescription: "Cute bed set",
        price: "Rp 7.000.000",
        fixPrice: "Rp 14.000.000",
        review: "4.4",
        amounthReview: "456",
        customerReview: "6",
        sku: "SS007",
        category: "Bed",
        tags: "Bed, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images8,
        img1: Images8,
        img2: Images8,
        img3: Images8,
        img4: Images8,
        discount:  "",
        newItem: "New",
        productName: "Potty",
        shortDescription: "Minimalist flower pot",
        price: "Rp 500.000",
        fixPrice: "",
        review: "4.4",
        amounthReview: "156",
        customerReview: "2",
        sku: "SS008",
        category: "Flower",
        tags: "Flower, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images1,
        img1: Images1,
        img2: Images1,
        img3: Images1,
        img4: Images1,
        discount: "-30%",
        newItem: "",
        productName: "Syltherine",
        shortDescription: "Stylish cafe chair",
        price: "Rp 2.500.000",
        fixPrice: "Rp 3.500.000",
        review: "4.7",
        amounthReview: "200",
        customerReview: "4",
        sku: "SS001",
        category: "Sofas",
        tags: "Sofa, Chair, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images2,
        img1: Images2,
        img2: Images2,
        img3: Images2,
        img4: Images2,
        discount: "-30%",
        newItem: "",
        productName: "Leviosa",
        shortDescription: "Stylish cafe chair",
        price: "Rp 2.500.000",
        fixPrice: "Rp 3.500.000",
        review: "4.6",
        amounthReview: "205",
        customerReview: "3",
        sku: "SS002",
        category: "Chair",
        tags: "Sofa, Chair, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images3,
        img1: Images3,
        img2: Images3,
        img3: Images3,
        img4: Images3,
        discount: "-50%",
        newItem: "",
        productName: "Lolito",
        shortDescription: "Luxury big sofa",
        price: "Rp 7.000.000",
        fixPrice: "Rp 14.000.000",
        review: "4.8",
        amounthReview: "405",
        customerReview: "8",
        sku: "SS003",
        category: "Sofa",
        tags: "Sofa, Chair, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images4,
        img1: Images4,
        img2: Images4,
        img3: Images4,
        img4: Images4,
        discount:  "",
        newItem: "New",
        productName: "Respira",
        shortDescription: "Outdoor bar table and stool",
        price: "Rp 500.000",
        fixPrice: "",
        review: "4",
        amounthReview: "105",
        customerReview: "2",
        sku: "SS004",
        category: "Table",
        tags: "Table, Chair, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images5,
        img1: Images5,
        img2: Images5,
        img3: Images5,
        img4: Images5,
        discount:  "",
        newItem: "",
        productName: "Grifo",
        shortDescription: "Night lamp",
        price: "Rp 1.500.000",
        fixPrice: "",
        review: "4.3",
        amounthReview: "156",
        customerReview: "3",
        sku: "SS005",
        category: "Lamp",
        tags: "Lamp, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images6,
        img1: Images6,
        img2: Images6,
        img3: Images6,
        img4: Images6,
        discount:  "",
        newItem: "New",
        productName: "Muggo",
        shortDescription: "Small mug",
        price: "Rp 1.500.000",
        fixPrice: "",
        review: "5",
        amounthReview: "456",
        customerReview: "5",
        sku: "SS006",
        category: "Mug",
        tags: "Mug, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images7,
        img1: Images7,
        img2: Images7,
        img3: Images7,
        img4: Images7,
        discount:  "-50%",
        newItem: "",
        productName: "Pingky",
        shortDescription: "Cute bed set",
        price: "Rp 7.000.000",
        fixPrice: "Rp 14.000.000",
        review: "4.4",
        amounthReview: "456",
        customerReview: "6",
        sku: "SS007",
        category: "Bed",
        tags: "Bed, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images8,
        img1: Images8,
        img2: Images8,
        img3: Images8,
        img4: Images8,
        discount:  "",
        newItem: "New",
        productName: "Potty",
        shortDescription: "Minimalist flower pot",
        price: "Rp 500.000",
        fixPrice: "",
        review: "4.4",
        amounthReview: "156",
        customerReview: "2",
        sku: "SS008",
        category: "Flower",
        tags: "Flower, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images1,
        img1: Images1,
        img2: Images1,
        img3: Images1,
        img4: Images1,
        discount: "-30%",
        newItem: "",
        productName: "Syltherine",
        shortDescription: "Stylish cafe chair",
        price: "Rp 2.500.000",
        fixPrice: "Rp 3.500.000",
        review: "4.7",
        amounthReview: "200",
        customerReview: "4",
        sku: "SS001",
        category: "Sofas",
        tags: "Sofa, Chair, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images2,
        img1: Images2,
        img2: Images2,
        img3: Images2,
        img4: Images2,
        discount: "-30%",
        newItem: "",
        productName: "Leviosa",
        shortDescription: "Stylish cafe chair",
        price: "Rp 2.500.000",
        fixPrice: "Rp 3.500.000",
        review: "4.6",
        amounthReview: "205",
        customerReview: "3",
        sku: "SS002",
        category: "Chair",
        tags: "Sofa, Chair, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images3,
        img1: Images3,
        img2: Images3,
        img3: Images3,
        img4: Images3,
        discount: "-50%",
        newItem: "",
        productName: "Lolito",
        shortDescription: "Luxury big sofa",
        price: "Rp 7.000.000",
        fixPrice: "Rp 14.000.000",
        review: "4.8",
        amounthReview: "405",
        customerReview: "8",
        sku: "SS003",
        category: "Sofa",
        tags: "Sofa, Chair, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images4,
        img1: Images4,
        img2: Images4,
        img3: Images4,
        img4: Images4,
        discount:  "",
        newItem: "New",
        productName: "Respira",
        shortDescription: "Outdoor bar table and stool",
        price: "Rp 500.000",
        fixPrice: "",
        review: "4",
        amounthReview: "105",
        customerReview: "2",
        sku: "SS004",
        category: "Table",
        tags: "Table, Chair, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images5,
        img1: Images5,
        img2: Images5,
        img3: Images5,
        img4: Images5,
        discount:  "",
        newItem: "",
        productName: "Grifo",
        shortDescription: "Night lamp",
        price: "Rp 1.500.000",
        fixPrice: "",
        review: "4.3",
        amounthReview: "156",
        customerReview: "3",
        sku: "SS005",
        category: "Lamp",
        tags: "Lamp, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images6,
        img1: Images6,
        img2: Images6,
        img3: Images6,
        img4: Images6,
        discount:  "",
        newItem: "New",
        productName: "Muggo",
        shortDescription: "Small mug",
        price: "Rp 1.500.000",
        fixPrice: "",
        review: "5",
        amounthReview: "456",
        customerReview: "5",
        sku: "SS006",
        category: "Mug",
        tags: "Mug, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images7,
        img1: Images7,
        img2: Images7,
        img3: Images7,
        img4: Images7,
        discount:  "-50%",
        newItem: "",
        productName: "Pingky",
        shortDescription: "Cute bed set",
        price: "Rp 7.000.000",
        fixPrice: "Rp 14.000.000",
        review: "4.4",
        amounthReview: "456",
        customerReview: "6",
        sku: "SS007",
        category: "Bed",
        tags: "Bed, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images8,
        img1: Images8,
        img2: Images8,
        img3: Images8,
        img4: Images8,
        discount:  "",
        newItem: "New",
        productName: "Potty",
        shortDescription: "Minimalist flower pot",
        price: "Rp 500.000",
        fixPrice: "",
        review: "4.4",
        amounthReview: "156",
        customerReview: "2",
        sku: "SS008",
        category: "Flower",
        tags: "Flower, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images1,
        img1: Images1,
        img2: Images1,
        img3: Images1,
        img4: Images1,
        discount: "-30%",
        newItem: "",
        productName: "Syltherine",
        shortDescription: "Stylish cafe chair",
        price: "Rp 2.500.000",
        fixPrice: "Rp 3.500.000",
        review: "4.7",
        amounthReview: "200",
        customerReview: "4",
        sku: "SS001",
        category: "Sofas",
        tags: "Sofa, Chair, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images2,
        img1: Images2,
        img2: Images2,
        img3: Images2,
        img4: Images2,
        discount: "-30%",
        newItem: "",
        productName: "Leviosa",
        shortDescription: "Stylish cafe chair",
        price: "Rp 2.500.000",
        fixPrice: "Rp 3.500.000",
        review: "4.6",
        amounthReview: "205",
        customerReview: "3",
        sku: "SS002",
        category: "Chair",
        tags: "Sofa, Chair, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images3,
        img1: Images3,
        img2: Images3,
        img3: Images3,
        img4: Images3,
        discount: "-50%",
        newItem: "",
        productName: "Lolito",
        shortDescription: "Luxury big sofa",
        price: "Rp 7.000.000",
        fixPrice: "Rp 14.000.000",
        review: "4.8",
        amounthReview: "405",
        customerReview: "8",
        sku: "SS003",
        category: "Sofa",
        tags: "Sofa, Chair, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images4,
        img1: Images4,
        img2: Images4,
        img3: Images4,
        img4: Images4,
        discount:  "",
        newItem: "New",
        productName: "Respira",
        shortDescription: "Outdoor bar table and stool",
        price: "Rp 500.000",
        fixPrice: "",
        review: "4",
        amounthReview: "105",
        customerReview: "2",
        sku: "SS004",
        category: "Table",
        tags: "Table, Chair, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images5,
        img1: Images5,
        img2: Images5,
        img3: Images5,
        img4: Images5,
        discount:  "",
        newItem: "",
        productName: "Grifo",
        shortDescription: "Night lamp",
        price: "Rp 1.500.000",
        fixPrice: "",
        review: "4.3",
        amounthReview: "156",
        customerReview: "3",
        sku: "SS005",
        category: "Lamp",
        tags: "Lamp, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images6,
        img1: Images6,
        img2: Images6,
        img3: Images6,
        img4: Images6,
        discount:  "",
        newItem: "New",
        productName: "Muggo",
        shortDescription: "Small mug",
        price: "Rp 1.500.000",
        fixPrice: "",
        review: "5",
        amounthReview: "456",
        customerReview: "5",
        sku: "SS006",
        category: "Mug",
        tags: "Mug, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images7,
        img1: Images7,
        img2: Images7,
        img3: Images7,
        img4: Images7,
        discount:  "-50%",
        newItem: "",
        productName: "Pingky",
        shortDescription: "Cute bed set",
        price: "Rp 7.000.000",
        fixPrice: "Rp 14.000.000",
        review: "4.4",
        amounthReview: "456",
        customerReview: "6",
        sku: "SS007",
        category: "Bed",
        tags: "Bed, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images8,
        img1: Images8,
        img2: Images8,
        img3: Images8,
        img4: Images8,
        discount:  "",
        newItem: "New",
        productName: "Potty",
        shortDescription: "Minimalist flower pot",
        price: "Rp 500.000",
        fixPrice: "",
        review: "4.4",
        amounthReview: "156",
        customerReview: "2",
        sku: "SS008",
        category: "Flower",
        tags: "Flower, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images1,
        img1: Images1,
        img2: Images1,
        img3: Images1,
        img4: Images1,
        discount: "-30%",
        newItem: "",
        productName: "Syltherine",
        shortDescription: "Stylish cafe chair",
        price: "Rp 2.500.000",
        fixPrice: "Rp 3.500.000",
        review: "4.7",
        amounthReview: "200",
        customerReview: "4",
        sku: "SS001",
        category: "Sofas",
        tags: "Sofa, Chair, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images2,
        img1: Images2,
        img2: Images2,
        img3: Images2,
        img4: Images2,
        discount: "-30%",
        newItem: "",
        productName: "Leviosa",
        shortDescription: "Stylish cafe chair",
        price: "Rp 2.500.000",
        fixPrice: "Rp 3.500.000",
        review: "4.6",
        amounthReview: "205",
        customerReview: "3",
        sku: "SS002",
        category: "Chair",
        tags: "Sofa, Chair, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images3,
        img1: Images3,
        img2: Images3,
        img3: Images3,
        img4: Images3,
        discount: "-50%",
        newItem: "",
        productName: "Lolito",
        shortDescription: "Luxury big sofa",
        price: "Rp 7.000.000",
        fixPrice: "Rp 14.000.000",
        review: "4.8",
        amounthReview: "405",
        customerReview: "8",
        sku: "SS003",
        category: "Sofa",
        tags: "Sofa, Chair, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images4,
        img1: Images4,
        img2: Images4,
        img3: Images4,
        img4: Images4,
        discount:  "",
        newItem: "New",
        productName: "Respira",
        shortDescription: "Outdoor bar table and stool",
        price: "Rp 500.000",
        fixPrice: "",
        review: "4",
        amounthReview: "105",
        customerReview: "2",
        sku: "SS004",
        category: "Table",
        tags: "Table, Chair, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images5,
        img1: Images5,
        img2: Images5,
        img3: Images5,
        img4: Images5,
        discount:  "",
        newItem: "",
        productName: "Grifo",
        shortDescription: "Night lamp",
        price: "Rp 1.500.000",
        fixPrice: "",
        review: "4.3",
        amounthReview: "156",
        customerReview: "3",
        sku: "SS005",
        category: "Lamp",
        tags: "Lamp, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images6,
        img1: Images6,
        img2: Images6,
        img3: Images6,
        img4: Images6,
        discount:  "",
        newItem: "New",
        productName: "Muggo",
        shortDescription: "Small mug",
        price: "Rp 1.500.000",
        fixPrice: "",
        review: "5",
        amounthReview: "456",
        customerReview: "5",
        sku: "SS006",
        category: "Mug",
        tags: "Mug, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images7,
        img1: Images7,
        img2: Images7,
        img3: Images7,
        img4: Images7,
        discount:  "-50%",
        newItem: "",
        productName: "Pingky",
        shortDescription: "Cute bed set",
        price: "Rp 7.000.000",
        fixPrice: "Rp 14.000.000",
        review: "4.4",
        amounthReview: "456",
        customerReview: "6",
        sku: "SS007",
        category: "Bed",
        tags: "Bed, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
    {
        img: Images8,
        img1: Images8,
        img2: Images8,
        img3: Images8,
        img4: Images8,
        discount:  "",
        newItem: "New",
        productName: "Potty",
        shortDescription: "Minimalist flower pot",
        price: "Rp 500.000",
        fixPrice: "",
        review: "4.4",
        amounthReview: "156",
        customerReview: "2",
        sku: "SS008",
        category: "Flower",
        tags: "Flower, Home, Shop",
        size1: "L",
        size2: "XL",
        size3: "XS",
    },
]
export default CardsData